### ISSUE TITLE
Development workflows

### ISSUE THREAD

**Issue by stonier** [maliput/maliput_infrastructure#139]
Support simpler and more flexible development workflows.

* **Work on an arbitrary subset of our repos** - e.g. delphyne/delphyne_gui only &rarr; simpler & flexibly handle different use cases
* **Dependency management via one tool** - simpler & shouldn't need to reinvent wheels (use or drive requirements for rosdep)
* **Minimise non-system dependencies** - too much endeavour to maintain
* **Minimise bundling of packages** - e.g. `tinyxml \in odm \in malidrive` &rarr; enable dependency sharing & avoid release incompatibilities

These are essentially the precepts of the ROS federated ecosystem. It's a set of rules that works and enables scaling and flexibility. Just a bit trickier to handle with closed source packages sans a build farm, but it's doable. I believe it is a good goal.

FYI @scpeters just to kick-start the thread.

**Comment by francocipollone** [comment]
Closing as all the tasks were finished
