### ISSUE TITLE
Use system pybind11 instead of custom version.

### ISSUE THREAD

**Issue by agalbachicar** [maliput/maliput_infrastructure#225]
Evaluate whether using pybind11 directly from packages is feasible. Touch points in code are:
  - maliput_py -> `api`, `math`, `plugin`
  - dragway
  - delphyne
  - delphyne_demos

Reason: it would prevent users to use TRI's fork of pybind11 stick to certain commit and simplify CI, set up and one dependency less to track.

Challenges:
- Compatibility in packages having drake_vendor as a dependency and their children.
- Different versions between focal (`pybind11 2.4.3-2`) and bionic (`pybind11 2.0.1-4`).
- Compiler support (both versions claim to have gcc 4.8 support and clang 3.3 (focal) and old clang version with C++11 support).

Parent issue https://github.com/ToyotaResearchInstitute/maliput_infrastructure/issues/139

**Comment by francocipollone** [comment]
@agalbachicar  The other we discussed the possibility of relying on pybind11 debian version if we re-adapt the api for those cases where the use of `std::unique_ptr` is an issue, which is, during construction (`_init_`)

Reviewing the `maliput_py` package we can see that we use them:
1. [Road Network's init method
](https://github.com/maliput/maliput_py/blob/a4fbac0f0a948e788d117d886ed26d3b13567660/src/bindings/api_py.cc#L137-L144)
```cpp
  py::class_<api::RoadNetwork>(m, "RoadNetwork")
      .def(
          py::init<std::unique_ptr<const api::RoadGeometry>, std::unique_ptr<const api::rules::RoadRulebook>,
                   std::unique_ptr<const api::rules::TrafficLightBook>, std::unique_ptr<api::IntersectionBook>,
                   std::unique_ptr<api::rules::PhaseRingBook>, std::unique_ptr<api::rules::RightOfWayRuleStateProvider>,
                   std::unique_ptr<api::rules::PhaseProvider>, std::unique_ptr<api::rules::RuleRegistry>,
                   std::unique_ptr<api::rules::DiscreteValueRuleStateProvider>,
                   std::unique_ptr<api::rules::RangeValueRuleStateProvider>>(),
          py::arg("road_geometry"), py::arg("rulebook"), py::arg("traffic_light_book"), py::arg("intersection_book"),
          py::arg("phase_ring_book"), py::arg("right_of_way_rule_state_provider"), py::arg("phase_provider"),
          py::arg("rule_registry"), py::arg("discrete_value_rule_state_provider"),
          py::arg("range_value_rule_state_provider"))
      .def("road_geometry", &api::RoadNetwork::road_geometry, py::return_value_policy::reference_internal)
```

2. [BulbGroup's init method](https://github.com/maliput/maliput_py/blob/a4fbac0f0a948e788d117d886ed26d3b13567660/src/bindings/api_rules_py.cc#L333-L338)
```cpp
      py::class_<rules::BulbGroup>(*m, "BulbGroup")
          .def(py::init<const rules::BulbGroup::Id&, const maliput::api::InertialPosition&,
                        const maliput::api::Rotation&, std::vector<std::unique_ptr<rules::Bulb>>>(),
               py::arg("id"), py::arg("position_traffic_light"), py::arg("orientation_traffic_light"), py::arg("bulbs"))
          .def("id", &rules::BulbGroup::id, py::return_value_policy::reference)
```
3. [TrafficLIght's init method](https://github.com/maliput/maliput_py/blob/a4fbac0f0a948e788d117d886ed26d3b13567660/src/bindings/api_rules_py.cc#L356-L362)
```cpp
  auto traffic_light_type =
      py::class_<rules::TrafficLight>(*m, "TrafficLight")
          .def(py::init<const rules::TrafficLight::Id&, const maliput::api::InertialPosition&,
                        const maliput::api::Rotation&, std::vector<std::unique_ptr<rules::BulbGroup>>>(),
               py::arg("id"), py::arg("position_road_network"), py::arg("orientation_road_network"),
               py::arg("bulb_groups"))
          .def("id", &rules::TrafficLight::id, py::return_value_policy::reference)
```

**Note: In `delphyne` it is used for several classes constructors for the `AgentSimulation` class**

### Proposal

Change the api if needed to avoid having bindings that receives `std::unique_ptr`s in the constructor

**Comment by francocipollone** [comment]
I am thinking of a solution for 2 and 3, if we could avoid modifying cpp's api would be great, or at least minimum impact.

**Comment by francocipollone** [comment]
> The three classes are final and don't have a hierarchy behind them. Also, there shouldn't be any reason to create bulbs beyond what is already built by the backend, so we could avoid the bindings for the moment, right?

I agree. So 1,2 and 3 would be solved the same way, with a decent TODO to be added back for consistency when moving to jammy.

I think that up-to here we could not rely on custom pybind11 version. (I've tested it locally). Delphyne would be still relying on custom `pybind` version, and we can tackle this later on.

### Next steps
#### First iteration
- [ ] As constructor bindings for 1, 2 and 3 aren't expected to be used we could just replace for a TODO.
- [ ] Change dependency from custom pybind11 to pybind11-dev which is installed via rosdep. 
    - [ ] maliput_py and maliput_object_py
    - [ ] CI: dependencies.repos file for those repos and downstream repos should be updated.
- [ ] Repos file in `maliput_infrastructure` should be modified, and pybind11 should be added to delphyne.repos file.
#### Second iteration
- [ ] Propose and implement an alternative for AgentSimulation's constructors.
- [ ] Switch to use debian instead for delphyne repos as well

@agalbachicar wdyt?

**Comment by agalbachicar** [comment]
Sounds like a great plan!

**Comment by francocipollone** [comment]
There is a point we are omitting and is actually a "convenient" thing.

`drake` brings its own pybind11 version with its installation(which happens to be the same custom pybind11 version from robotlocomotion). So for `delphyne` repos, given that we are actually relying on drake, we don't need to actually install from source pybind11, as it is already part of `/opt/drake/../pybind11`.

Having said this, we can remove custom pybind11 repository directly from our workspace.

**Comment by agalbachicar** [comment]
Yeah, but us it a good thing to do? I'd rather consider a way to not depend on the custom pybind at all or be explicit on the non-standard dependency instead of hiding it.

**Comment by francocipollone** [comment]
> Yeah, but us it a good thing to do? I'd rather consider a way to not depend on the custom pybind at all or be explicit on the non-standard dependency instead of hiding it.

As we chat F2F, I will proceed on letting delphyne to consume drake's pybind11 version, but explicitly call find_pcakage and leave a comment with the current behavior.
