### ISSUE TITLE
Enable DCO for all the repositories

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_infrastructure#264]
### Summary
DCO should be enabled for all the repositories and should be a request for merging the PRs.
- [x] maliput
- [ ] maliput_py
- [ ] maliput_object
- [ ] maliput_dragway
- [ ] maliput_multilane
- [ ] maliput_malidrive
- [ ] maliput_integration
- [ ] maliput_integration_tests
- [ ] maliput_drake
- [ ] delphyne
- [ ] delphyne_gui
- [ ] delphyne_demos
- [ ] maliput_documentation
- [ ] maliput_infrastructure

**Comment by francocipollone** [comment]
@tfoote I will continue activating DCO in the rest of the repos if that's ok

**Comment by tfoote** [comment]
Double check. I thought that I turned it on for the whole organization.

**Comment by francocipollone** [comment]
You are correct! They are part of the github apps for all the repos. I wasn't familiarized with the process! Thanks.
Closing then
