### ISSUE TITLE
[META] Maliput repos in the ROS build farm

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_infrastructure#269]
### Introduction
This issue's goal is to track the inclusion of the maliput repos into the ros build farm.

### Ros build farm info
 - Jobs are run at https://build.ros2.org/
 - Everything there comes from the index: https://github.com/ros/rosdistro
   - For foxy: https://github.com/ros/rosdistro/blob/master/foxy/distribution.yaml
 - Example with [ament_cmake](https://github.com/ros/rosdistro/blob/d73c33708a5794ce6895863e0a5ed1a425889640/foxy/distribution.yaml#L35)
   - 1. `doc`: It will generate the documentation jobs: [Resultant doc job](https://build.ros2.org/job/Hdoc__ament_cmake__ubuntu_jammy_amd64/)
   - 2. `release`. That comes from running [bloom](http://wiki.ros.org/bloom/Tutorials)
   - 3. `source` By default Dev jobs are enabled testing changes to `main`. and `test_pull_requests` enables PR testing.
      - For PRs: This job is the Fpr https://build.ros2.org/job/Fpr__ament_cmake__ubuntu_focal_amd64/
      - Dev jobs: https://build.ros2.org/job/Fdev__ament_cmake__ubuntu_focal_amd64/ 
        - It tests the distro default branch on commit.
 - How to enable PR testing on a repo: http://wiki.ros.org/buildfarm/Pull%20request%20testing

### To be ros-build-farm compatible
 - #265
         Use `rosdoc2` instead of custom `ament_cmake_doxygen`
   While migrating to `rosdoc2`, as a workaround:
     - [ ] #273
 - [x] #270 
 - [x] #271
 - [ ] #275 
 - [x] #225
 - [x] #276
 - [x] Solve `drake_vendor` issue: Nowadays this package needs to manually run a bash script.
    Marked as solved as there are ongoing efforts for releasing drake.
### Summary

The following table shows which are the packages where `drake_vendor` and `pybind11` are blockers (with a :x:) for the build farm.
| **Repository** | **Drake vendor** | **Custom Pybind11** | **In ROSBuildFarm?** |
|---|---|---|---|
| **maliput** | :heavy_check_mark: | :heavy_check_mark: |  :heavy_check_mark: |
| **maliput_py** | :heavy_check_mark: | :x: --> :heavy_check_mark:| :heavy_check_mark: |
| **maliput_drake** | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| **maliput_dragway** | :heavy_check_mark: | :x: --> :heavy_check_mark: |  :heavy_check_mark:  |
| **maliput_multilane** | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| **maliput_malidrive** | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| **maliput_object** | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| **maliput_object_py** | :heavy_check_mark: | :x: --> :heavy_check_mark: | :heavy_check_mark: |
| **maliput_integration** | :heavy_check_mark: | :x: --> :heavy_check_mark: | :heavy_check_mark: |
| **maliput_integration_tests** | :heavy_check_mark: | :x: --> :heavy_check_mark: | :heavy_check_mark:(Just source) |
| **delphyne** | :x: | :x: |  |
| **delphyne_gui** | :x: | :x: |  |
| **delphyne_demos** | :x: | :x: |  |

**Comment by francocipollone** [comment]
Does it make sense to add `maliput_integration_tests` to the build farm? 
@tfoote @agalbachicar

**Comment by tfoote** [comment]
If it's just tests it doesn't make sense to release. As the tests won't be installed usually because they are designed to work in the source tree. But you could add the source entry to the rosdistro and enable pull request testing on it to get ci from the farm.

**Comment by francocipollone** [comment]
> If it's just tests it doesn't make sense to release. As the tests won't be installed usually because they are designed to work in the source tree. But you could add the source entry to the rosdistro and enable pull request testing on it to get ci from the farm.

Agree! For doing so, should I manually create PR in rosdistro for adding something like:
```
  maliput_integration_tests:
    source:
      test_pull_requests: true
      type: git
      url: https://github.com/maliput/maliput_integration_tests.git
      version: main
```
or can I use the `bloom-release` tool, avoiding all the steps related to the release repository and docs?

**Comment by francocipollone** [comment]
> A manual PR with the above content is the easiest way. Bloom is really for the release tags. and does the other ones for convenience. There's no need to use it if not making the release.

Thanks for the clarification: Done -> https://github.com/ros/rosdistro/pull/33677

**Comment by francocipollone** [comment]
I tried installing them via apt. While they aren't part in `main` in the ros2 repository, we can use the `ros-testing` branch for try them out. See [testing](https://docs.ros.org/en/rolling/Installation/Testing.html)


The only conflict I found is related to environment variables after doing source `/opt/ros/foxy/setup.bash`:
maliput-related environment variables aren't pointing correctly to the path:

```
franco@aerilon $ env | grep maliput
MALIPUT_PLUGIN_PATH=/maliput_malidrive/lib/plugins:/maliput_multilane/lib/plugins:/maliput_dragway/lib/plugins
MALIPUT_MALIDRIVE_RESOURCE_ROOT=/maliput_malidrive/share/maliput_malidrive
MULTILANE_RESOURCE_ROOT=/maliput_multilane/share/maliput_multilane
```

We are using `MALIPUT_MALIDRIVE_RESOURCE_ROOT $COLCON_PREFIX_PATH/maliput_malidrive/share/maliput_malidrive` when adding the env var. See [maliput_malidrive/setup.sh.in
](https://github.com/maliput/maliput_malidrive/blob/main/setup.sh.in#L84)
but I think we should use `AMENT_CURRENT_PREFIX` instead.

**Comment by francocipollone** [comment]
Closing this meta issue and leaving the pendings at: https://github.com/maliput/maliput_infrastructure/issues/291
