### ISSUE TITLE
Provide a Meta-package that contains all the maliput repositories

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_infrastructure#279]
### Summary

Provide a package (maliput-full? maliput-all?) that depends on all the maliput repositories. 
The idea is to make it easier for users to install maliput repositories.
In a way that, once it is part of the ros build farm and it is added to the foxy index, by doing `sudo apt install maliput-all` you can bring all the maliput repos.

We can start with:
 - maliput
 - maliput_py
 - maliput_object
 - maliput_object_py
 - maliput_dragway
 - maliput_drake
 - maliput_multilane
 - maliput_malidrive
 - maliput_integration
 
 Once they are available we could move on to also include delphyne repos.
 
 ### Suggestion
 This meta-package can be added to this `maliput_infrastructure` repository.

**Comment by francocipollone** [comment]
We discussed this f2f with @tfoote yesterday, wdyt @agalbachicar @stonier @andrewbest-tri @liangfok

**Comment by andrewbest-tri** [comment]
LGTM

**Comment by tfoote** [comment]
I'd suggest -full to echo desktop-full
