### ISSUE TITLE
Triage CI workflow failing for some PRs

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_infrastructure#286]
## Summary
https://github.com/maliput/maliput_infrastructure/pull/285

Triage workflow is failing for PRs https://github.com/maliput/maliput_infrastructure/pull/285 and https://github.com/maliput/maliput_documentation/pull/114

![image](https://user-images.githubusercontent.com/53065142/193865372-48b5d06a-97c0-4271-b0f7-e7afcd16be83.png)

**Comment by francocipollone** [comment]
Wondering if it is related that the PRs are created from a fork. (I hadn't tried that before.)

**Comment by liangfok** [comment]
Here are the instructions that ask users to create forks:

> Fork the Maliput package you want to contribute to. This will create your own personal copy of the package. All of your development should take place in your fork. - An important thing to do is create a remote pointing to the [upstream remote repository](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork) . This way, you can always check for modifications on the original repository and always keep your fork repository up to date.

https://maliput.readthedocs.io/en/latest/contributing.html#contributing-code

**Comment by francocipollone** [comment]
It is related to the github token being passed when the PR is created from a fork:

Solved at
- https://github.com/maliput/maliput_documentation/pull/116
Using [`pull_request_target`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target) event instead.
This event uses the context of the base branch.

Evidence that it is now working
- PR from a fork: https://github.com/maliput/maliput_documentation/pull/117
- PR from the same repo: https://github.com/maliput/maliput_documentation/pull/118

We should propagate this change to all the repositories!
- [x] maliput_documentation 
- [ ] maliput_infrastructure 
- [ ] maliput
- [ ] maliput_py
...
...
