### ISSUE TITLE
Add maliput_viz to the repos file

### ISSUE THREAD

**Issue by agalbachicar** [maliput/maliput_infrastructure#295]
## Desired behavior

Add maliput_viz to the repos file under foxy.

**Comment by francocipollone** [comment]
it is here: https://github.com/maliput/maliput_infrastructure/pull/294

**Comment by francocipollone** [comment]
That PR is stuck until this is merged: https://github.com/ros/rosdistro/pull/35641

**Comment by agalbachicar** [comment]
Argh, sorry for that. I've just updated the workspace and missed it.
