### ISSUE TITLE
Migrate to newer github action components to avoid deprecation warnings

### ISSUE THREAD

**Issue by agalbachicar** [maliput/maliput_infrastructure#319]
## Desired behavior
Most of the actions/checkout, actions/upload-artifact and alike components are pinned to the latest v3 version. We need to move to v4 to avoid deprecation warnings related to Node.js.

## Alternatives considered
N/A

## Implementation suggestion
N/A

## Additional context
See https://github.com/maliput/maliput_py/actions/runs/7782058733 for example.

https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Due date: 2024/06/30

**Comment by agalbachicar** [comment]
- [ ] maliput
- [ ] maliput_dragway
- [ ] maliput_multilane
- [ ] maliput_malidrive
- [ ] maliput_sparse
- [ ] maliput_py
- [ ] maliput_integration
- [ ] maliput_integration_test
- [ ] maliput_object
- [ ] maliput_object_py
- [ ] maliput_osm
- [ ] maliput_sim
- [ ] maliput_viz
- [ ] maliput_xodr
- [ ] delphyne
- [ ] delphyne_demos
- [ ] delphyne_gui
- [ ] lanelets_eval
- [ ] maliput-rs

**Comment by agalbachicar** [comment]
Making use of the occasion to update other actions as well:

- actions/checkout@v4
- actions/upload-artifact@v4
- ros-tooling/setup-ros@v0.7
- codecov/codecov-action@v4
- docker/login-action@v3
- docker/metadata-action@v5
- docker/build-push-action@v5
- softprops/action-gh-release@v2
- ros-tooling/action-ros-ci@v0.3

**Comment by agalbachicar** [comment]
Curiously, all workflows using the manylinux image failed. That is related to a glibc library version installed in the image which collides with a node dependency required by actions/checkout@v4. Seems like sticking to v3 for now is the only way moving forward.

In particular, the manylinux image has glibc-2.17-326.el7_9.x86_64 and the requirement is for glibc 2.25+.

**Comment by francocipollone** [comment]
> Curiously, all workflows using the manylinux image failed. That is related to a glibc library version installed in the image which collides with a node dependency required by actions/checkout@v4. Seems like sticking to v3 for now is the only way moving forward.
> 
> In particular, the manylinux image has glibc-2.17-326.el7_9.x86_64 and the requirement is for glibc 2.25+.

Until November 30, 2024 we are ok: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
